name: run

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions: write-all

jobs:
  run:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: 'Install Groovy'
        id: install-groovy
        run: |
          sudo apt install groovy
          groovy --version
      
      - name: 'Run and commit'
        id: read-targets
        run: |
          
          groovy main.groovy "${{secrets.DROPBOXFILE}}" "${{secrets.WRITEURL}}"

          git config user.email "github@plaintext.ch"
          git config user.name "GithubActions"
          
          git add old.hash
          if ! git diff-index --quiet HEAD; then
            git commit -m "Update old.hash [skip-ci]"
            git push
          fi
        